"""Initial schema: users, api_keys, memories with pgvector, tsvector, HNSW,
partial dedup index and Row-Level Security policies.

DDL is written explicitly here (not autogenerated) because the schema uses
PostgreSQL features SQLAlchemy metadata would not emit faithfully: generated
tsvector columns, HNSW indexes, partial unique indexes and RLS policies.

Isolation model
---------------
- ``memories`` has RLS enabled **and forced** so even the table owner is
  subject to the policy (superusers and BYPASSRLS roles still bypass RLS by
  design; the application must therefore connect with a regular, non-superuser
  role). Every application statement runs after
  ``set_config('app.current_user_id', uid, true)`` (SET LOCAL), so a missing
  or wrong context yields zero rows instead of another user's memories.
- ``api_keys`` has RLS enabled but **not forced**. Authentication must resolve
  a bearer-token hash to a user *before* any user context can exist, which is
  impossible if the owner role is filtered by RLS during that lookup. The
  application still never returns key rows through the MCP surface; only the
  SHA-256 hash is persisted, and the admin CLI is the sole management path.
  If Recallum later adopts a non-owner connection role, FORCE can be added.
"""

from __future__ import annotations

from alembic import op

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.execute(
        """
        CREATE TABLE users (
            id         UUID PRIMARY KEY,
            username   TEXT NOT NULL UNIQUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE api_keys (
            id           UUID PRIMARY KEY,
            user_id      UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
            name         TEXT,
            key_hash     CHAR(64) NOT NULL UNIQUE,
            created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            last_used_at TIMESTAMPTZ,
            revoked_at   TIMESTAMPTZ
        )
        """
    )
    op.execute("CREATE INDEX ix_api_keys_user_id ON api_keys (user_id)")

    op.execute(
        """
        CREATE TABLE memories (
            id            UUID PRIMARY KEY,
            user_id       UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
            scope         TEXT NOT NULL CHECK (scope IN ('global', 'project')),
            project       TEXT,
            category      TEXT NOT NULL CHECK (
                              category IN ('preference', 'decision', 'constraint', 'fact')
                          ),
            content       TEXT NOT NULL,
            content_hash  CHAR(64) NOT NULL,
            embedding     vector(768) NOT NULL,
            importance    SMALLINT NOT NULL DEFAULT 5 CHECK (importance BETWEEN 0 AND 10),
            source_client TEXT,
            metadata      JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at    TIMESTAMPTZ,
            content_tsv   tsvector GENERATED ALWAYS AS (
                              to_tsvector('simple', content)
                          ) STORED,
            CHECK ((scope = 'project') = (project IS NOT NULL))
        )
        """
    )

    # Listing and filtering.
    op.execute(
        """
        CREATE INDEX ix_memories_user_active_created
            ON memories (user_id, created_at DESC)
            WHERE deleted_at IS NULL
        """
    )
    op.execute(
        """
        CREATE INDEX ix_memories_user_project
            ON memories (user_id, project)
            WHERE deleted_at IS NULL
        """
    )

    # Exact active-duplicate prevention per user, scope, project and content.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_memories_active_dedup
            ON memories (user_id, scope, COALESCE(project, ''), content_hash)
            WHERE deleted_at IS NULL
        """
    )

    # Semantic candidates: cosine-distance HNSW.
    op.execute(
        """
        CREATE INDEX ix_memories_embedding_hnsw
            ON memories USING hnsw (embedding vector_cosine_ops)
        """
    )

    # Textual candidates: GIN over the simple-config tsvector.
    op.execute(
        """
        CREATE INDEX ix_memories_content_tsv ON memories USING gin (content_tsv)
        """
    )

    # Row-Level Security: memories are hard-isolated (forced even for owner).
    op.execute("ALTER TABLE memories ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE memories FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY memories_user_isolation ON memories
            FOR ALL
            USING (user_id::text = current_setting('app.current_user_id', true))
            WITH CHECK (user_id::text = current_setting('app.current_user_id', true))
        """
    )

    # api_keys: policy ready for non-owner roles; not forced (see module note).
    op.execute("ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY api_keys_user_isolation ON api_keys
            FOR ALL
            USING (user_id::text = current_setting('app.current_user_id', true))
            WITH CHECK (user_id::text = current_setting('app.current_user_id', true))
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS memories")
    op.execute("DROP TABLE IF EXISTS api_keys")
    op.execute("DROP TABLE IF EXISTS users")
    op.execute("DROP EXTENSION IF EXISTS vector")
